加入一些shoka配置细节以及文章yaml具体配置
theme-shoka-x/shokaX-docs pull request #3
Opened 2023-06-16 16:59 UTC by foryouos

加入一些shoka配置细节以及文章yaml具体配置，便于新用户使用，配置首页精选与翻转

2023-06-17 07:49 UTC, D-Sketon commented on docs/guide/theme.md
> +> 安装 `hexo-symbols-count-time`后，
shokax内嵌[symbols_count_time.ts](https://github.com/theme-shoka-x/hexo-theme-shokaX/blob/main/scripts/helpers/symbols_count_time.ts)，无需安装`hexo-symbols-count-time`

2023-06-17 08:16 UTC, foryouos commented on docs/guide/theme.md
> +> 安装 `hexo-symbols-count-time`后，
已修改

2023-06-17 09:19 UTC, zkz098 requested changes
有一点格式上的小问题

2023-06-17 09:19 UTC, zkz098 commented on docs/guide/tags.md
> +## 基础配置
这里单独设立一个front-matter区域更好
```suggestion
## Front-matter
```
同时把这一部分放到MD标签之前

2023-06-17 09:19 UTC, zkz098 commented on docs/guide/tags.md
> +* sticky  : true 文章置顶 多篇文章按照发布时间倒序排列，不分页
```suggestion
* sticky  : 当设置为`true`时此篇文章置顶 ，如果置顶多篇文章按照发布时间倒序排列，不分页
```

2023-06-17 09:19 UTC, zkz098 commented on docs/guide/tags.md
> +* audio   : 文章背景音乐(覆盖全局) false 关闭背景音乐
```suggestion
* audio   : 文章背景音乐 (覆盖全局) 当设置为`false`时关闭背景音乐
```

2023-06-17 09:19 UTC, zkz098 commented on docs/guide/theme.md
> +![image](https://github.com/foryouos/shokaX-docs/assets/58133210/3d81cebf-0a39-4fa7-8ea1-d64dacc3a6cc)
image直接放到文章对应目录下，然后使用相对链接即可，走github比较影响国内用户体验

2023-06-17 09:19 UTC, zkz098 commented on docs/guide/theme.md
> +![如图所示的布局](https://github.com/foryouos/shokaX-docs/assets/58133210/f8d8c514-61f1-4495-bb24-1a52a654f797 "如图所示的布局")
这个image也改一下，放到文章目录下

2023-06-17 09:19 UTC, zkz098 commented on docs/guide/theme.md
> +### 实验性特性
长文章优化是实验性特性下的，应该使用`####`放在下面那个tip的后面

2023-06-17 09:19 UTC, zkz098 commented on docs/guide/tags.md
> +```markdown
```suggestion
```yaml
```
yaml更符合这个代码块的语言特点

2023-06-17 09:19 UTC, zkz098 commented on docs/guide/theme.md
> +###
```suggestion

```
这里有一个空标题

2023-06-18 00:11 UTC, foryouos reviewed
更改

2023-06-18 00:11 UTC, foryouos commented on docs/guide/theme.md
> +### 实验性特性
已修改

2023-06-18 00:11 UTC, foryouos commented on docs/guide/theme.md
> +![image](https://github.com/foryouos/shokaX-docs/assets/58133210/3d81cebf-0a39-4fa7-8ea1-d64dacc3a6cc)
已修改，(下一次得建立个文件文件夹啦)

2023-06-18 06:20 UTC, zkz098 approved these changes

2023-06-18 06:20 UTC, merged